#!/usr/bin/env perl
use strict;
use warnings;
use lib 'lib/';
use TCNPerlVars;
use Getopt::Long;
use Cwd;
$TCNPerlVars::extPackDir = getcwd() . '/extpackages';

my $force = 0;
GetOptions("f" => \$force);

system("mkdir -p $TCNPerlVars::blastdbDir");
if($?){
  print "Failed to create blastdb directory $TCNPerlVars::blastdbDir, $!\n";
}

if(-e $TCNPerlVars::blastdbDir . "/swissprot.phr" && ! $force){
    print <<EOF;
It looks like a swissprot db has already been set up in $TCNPerlVars::blastdbDir, so I won't continue.
Use the -f option to download and format the latest swissprot file from the NCBI. You may want to save the old version of the database if you so need!
EOF
exit(1);
}

print "Getting swissprot file from NCBI FTP server ...\n";
system("wget -O $TCNPerlVars::blastdbDir/swissprot.gz ftp://ftp.ncbi.nlm.nih.gov/blast/db/FASTA/swissprot.gz");

chdir($TCNPerlVars::blastdbDir);
print "Decompressing file ...\n";
system("gzip -d swissprot.gz");

print "Creating db from file ...\n";
system("$TCNPerlVars::extPackDir/blast-2.2.22/bin/formatdb -i swissprot");

print "Done!\n";
