>P1;APOD_RABIT
, 209 bases
 MAPTLLLLLP ALAGLISVAQ GQAFHLGRCP TPPVQENFDV HKYLGRWYEI
 EKI-PVSFEK GNCIQANYSL MENGNIKVLN QE----LRPD GTVNQIEGQA
 TQSNLTEPAK LGVKFFQLMP -----TAPYW VLATDYENYA LVYSC--TTI
 IWLFHMDHVW ILGRNRY-LP PETVTYLKDI LTANNIDIEK MTVTD-QVNC
 PEF------*

>P1;RET4_HUMAN
, 209 bases
 MKWVWALLLL AALG-----S GRAERDCRVS SFRVKENFDK ARFSGTWYAM
 AKKDPEGLFL QDNIVAEFSV DETGQMSATA KGRVRLLNNW DVCADMVGTF
 T--DTEDPAK FKMKYWGVAS FLQKGNDDHW IVDTDYDTYA VQYSCRLLNL
 DGTCADSYSF VFSRDPNGLP PEAQKIVRQR QEELCLARQY RLIVH-NGYC
 DGRSERNLL*

>P1;APOD_MOUSE
, 209 bases
 -MVTMLMFLA TLAGLFTTAK GQNFHLGKCP SPPVQENFDV KKYLGRWYEI
 EKI-PASFEK GNCIQANYSL MENGNIEVLN KE----LSPD GTMNQVKGEA
 KQSNVSEPAK LEVQFFPLMP -----PAPYW ILATDYENYA LVYSC--TTF
 FWLFHVDFVW ILGRNPY-LP PETITYLKDI LTSNGIDIEK MTTTD-QANC
 PDFL-----*

>P1;LACB1_CANFA
, 209 bases
 ---------- ---------- --------IV VPRTMEDLDL QKVAGTWHSM
 AMA-ASDISL LDSETAPLRV YIQELRPTPQ DNLEIVLRKW EDGRCAEQKV
 LAEKTEVPAE FKINYVE--- -----ENQIF LLDTDYDNY- -LFFC-EMNA
 DAPQQSLMCQ CLARTLE-VD NEVMEKFNRA LKTLPVHMQL LNPTQAEEQC
 LI-------*

>P1;PURP_CHICK
, 209 bases
 MKYAQYVFL- --ASIFSAVE YSLAQTCAVD SFSVKDNFDP KRYAGKWYAL
 AKKDPEGLFL QDNISAEYTV EEDGTMTASS KGRVKLFGFW VICADMAAQY
 TVPDPTTPAK MYMTYQGLAS YLSSGGDNYW VIDTDYDNYA ITYACRSLKE
 DGSCDDGYSL IFSRNPRGLP PAIQRIVRQK QEEICMSGQF QPVLQ-SGAC
 ---------*

>P1;RET4_HORSE
, 209 bases
 MEWVWALVVL AALG-----S AGAERDCRVS SFRVKENFDK ARFSGTWYAM
 AKKDPEGLFL QDNIVAEFSV DEYGQMSATA KGRVRLLNNW DVCADMVGTF
 T--DTEDPAK FKMKYWGVAS FLQKGNDDHW IIDTDYDTYA VQYSCRLLNL
 DGTCADSYSF VFARDPNGFP PEVQRIVRRR QEELCLARQY RLISH-NGYC
 DGKSDRNLL*

>P1;RET4B_ONCMY
, 209 bases
 ---------- ---------- ----SDCQVS NIQVMQNFDR SRYTGRWYAV
 AKKDPVGLFL LDNVVAQFSV DGSGKVTATA QGRVIILNNW EMCANMFGTF
 E--DTPDPAK FKMRYWGAAA YLQSGNDDHW VIDTDYDNYA IHYSCREVDL
 DGTCLDGYSF IFSRHPTGLR PEDQKIVTDK KKELCFLGKY RRVSH-TGFC
 ESS------*

>P1;3bszF
, 209 bases
 ---------- ---------- ---ERDCRVS SFRVKENFDK ARFSGTWYAM
 AKKDPEGLFL QDNIVAEFSV DETGQMSATA KGRVRLLNNW DVCADMVGTF
 T--DTEDPAK FKMKYWGVAS FLQKGNDDHW IVDTDYDTYA VQYSCRLLNL
 DGTCADSYSF VFSRDPNGLP PEAQKIVRQR QEELCLARQY RLIVH-NGYC
 DG-------*

>P1;APOD_MACFA
, 209 bases
 -MVMLLLLLS ALAGLFGAAE GQEFRLGKCT SPPVQENFDP NKYFGRWYEI
 EKI-PTTFEK GRCIQANYSL KENGKIKVLN QE----LRAD GTVNQIEGEA
 SPVNITEPAK LEVKFFWFMP -----SAPYW VLATDYENYA LVYSC--VSI
 INLFRVDYAW ILARNRH-LP SETVDFLKNI LTSNNIDVKK MTVTD-QENC
 PEFS-----*

>P1;RET4_BOVIN
, 209 bases
 ---------- ---------- ---ERDCRVS SFRVKENFDK ARFAGTWYAM
 AKKDPEGLFL QDNIVAEFSV DENGHMSATA KGRVRLLNNW DVCADMVGTF
 T--DTEDPAK FKMKYWGVAS FLQKGNDDHW IIDTDYETFA VQYSCRLLNL
 DGTCADSYSF VFARDPSGFS PEVQKIVRQR QEELCLARQY RLIPH-NGYC
 DGKSERNIL*

>P1;APOD_RAT
, 209 bases
 -MATMLLLLA TLAGLFTTTE GQSFHLGKCP SPPVQENFDV KKYLGRWYEI
 EKI-PVSFEK GNCIQANYSL MENGNIKVLN KE----LRPD GTLNQVEGEA
 KQSNMSEPAK LEVQFFSLMP -----PAPYW ILATDYESYA LVYSC--TTF
 FWFFHVDYVW ILGRNPY-LP PETITYLKYI LTSNDIDIAK ITTKD-QANC
 PDFL-----*

>P1;RET4A_ONCMY
, 209 bases
 ---------- ---------- ----SDCQVS NIQVMQNFDR SRYTGRWYAV
 AKKDPVGLFL LDNVVAQFSV DESGKVTATA HGRVIILNNW EMCANMFGTF
 E--DTPDPAK FKMRYWGAAS YLQTGNDDHW VIDTDYDNYA IHYSCREVDL
 DGTCLDGYSF IFSRHPTGLR PEDQKIVTDK KKEICFLGKY RRVGH-TGFC
 ESS------*

>P1;RET4_CHICK
, 209 bases
 MAYTWRALLL LALAFLGSSM AE--RDCRVS SFKVKENFDK NRYSGTWYAM
 AKKDPEGLFL QDNVVAQFTV DENGQMSATA KGRVRLFNNW DVCADMIGSF
 T--DTEDPAK FKMKYWGVAS FLQKGNDDHW VVDTDYDTYA LHYSCRELNE
 DGTCADSYSF VFSRDPKGLP PEAQKIVRQR QIDLCLDRKY RVIVH-NGFC
 S--------*

>P1;APOD_HUMAN
, 209 bases
 -MVMLLLLLS ALAGLFGAAE GQAFHLGKCP NPPVQENFDV NKYLGRWYEI
 EKI-PTTFEN GRCIQANYSL MENGKIKVLN QE----LRAD GTVNQIEGEA
 TPVNLTEPAK LEVKFSWFMP -----SAPYW ILATDYENYA LVYSC--TCI
 IQLFHVDFAW ILARNPN-LP PETVDSLKNI LTSNNIDVKK MTVTD-QVNC
 PKLS-----*

>P1;RET4_XENLA
, 209 bases
 -MERKVLGLL IALGFLGSCL AE--KNCRVD NFEVMKDFNK ERYAGVWYAV
 AKKDPEGLFL LDNIAANFKI EDNGKTTATA KGRVRILDKL ELCANMVGTF
 I--ETNDPAK YRMKYHGALA ILERGLDDHW VVDTDYTTYA ITYACRRRNL
 DGTCRDSYSF VFSRDINGLP SESQRIVRRR QEQLCLDRKY RVVVH-NGYC
 ETN------*

>P1;APOD_CAVPO
, 209 bases
 -MGMMLLLLS MLAGLVAEAE GQAFHFGKCP NPPVQENFDL NKYLGRWYEI
 EKI-PVSFEK GNCIQANYSL KENGRVKVLN QE----LRPD GTVNQIEGEA
 THSNITEPAK LGVKFFQLMP -----SAPYW VLATDYDNYA LVYSC--TNI
 IWLFHVDHIW ILGRNRY-LP QETVTYLKDI LTSNNIDIEK MTLTD-QANC
 PDFL-----*

>P1;RET4_RAT
, 209 bases
 MEWVWALVLL AALG-----G GSAERDCRVS SFRVKENFDK ARFSGLWYAI
 AKKDPEGLFL QDNIIAEFSV DEKGHMSATA KGRVRLLSNW EVCADMVGTF
 T--DTEDPAK FKMKYWGVAS FLQRGNDDHW IIDTDYDTFA LQYSCRLQNL
 DGTCADSYSF VFSRDPNGLT PETRRLVRQR QEELCLERQY RWIEH-NGYC
 QSRPSRNSL*

>P1;RET4_RABIT
, 209 bases
 MEWVWALVLL AALG-----S GRGERDCRVS SFRVKENFDK ARFAGTWYAM
 AKKDPEGLFL QDNIVAEFSV DENGHMSATA KGRVRLLNNW DVCADMVGTF
 T--DTEDPAK FKMKYWGVAS FLQRGNDDHW IIDTDYDTFA VQYSCRLLNF
 DGTCADSYSF VFSRDPHGLP PDVQKLVRQR QEELCLSRQY RLIVH-NGYC
 DDKSVRNLL*

>P1;RET4_PANTR
, 209 bases
 MKWVWALLLL AALG-----S GRAERDCRVS SFRVKENFDK ARFSGTWYAM
 AKKDPEGLFL QDNIVAEFSV DETGQMSATA KGRVRLLNNW DVCADMVGTF
 T--DTEDPAK FKMKYWGVAS FLQKGNDDHW IVDTDYDTYA VQYSCRLLNL
 DGTCADSYSF VFSRDPNGLP PEAQKIVRQR QEELCLARQY RLIVH-NGYC
 DGRSERNLL*

>P1;APOD_BOVIN
, 209 bases
 -MVPVLLLLP ALAGLFGAAE GQAFHLGKCP HPPVQENFDV NKYLGKWYEI
 EKI-PVSFEK GSCIQANYSL KENGNVEVIN KE----LRAD GTVNQIEGEA
 TPENITEPAK LAVKFFWFMP -----SAPYW VLATDYENYA LVYSC--TTI
 IWLFHMDHVW ILGRNPY-LP PETVTYLKDI LTSNNIEVEK MTITD-QVNC
 PESM-----*

>P1;RET4_MOUSE
, 209 bases
 MEWVWALVLL AALG-----G GSAERDCRVS SFRVKENFDK ARFSGLWYAI
 AKKDPEGLFL QDNIIAEFSV DEKGHMSATA KGRVRLLSNW EVCADMVGTF
 T--DTEDPAK FKMKYWGVAS FLQRGNDDHW IIDTDYDTFA LQYSCRLQNL
 DGTCADSYSF VFSRDPNGLS PETRRLVRQR QEELCLERQY RWIEH-NGYC
 QSRPSRNSL*

>P1;RET4_PIG
, 209 bases
 MEWVWALVLL AALG-----S AQAERDCRVS SFRVKENFDK ARFSGTWYAM
 AKKDPEGLFL QDNIVAEFSV DENGHMSATA KGRVRLLNNW DVCADMVGTF
 T--DTEDPAK FKMKYWGVAS FLQKGNDDHW IIDTDYDTYA VQYSCRLQNL
 DGTCADSYSF VFARDPHGFS PEVQKIVRQR QEELCLARQY RIITH-NGYC
 DGKSERNIL*
